name: 'Fetch & Ingest 2019-nCov/SARS-CoV-2 data from GISAID for nextstrain.org/ncov'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # "At 07:00 (09:00 CET) on every day-of-week from Monday through Friday."
    - cron:  '0 7 * * MON-FRI'

  # Manually triggered using `./bin/trigger fetch-and-ingest`
  repository_dispatch:
    types: fetch-and-ingest

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: ingest
      run: |
        PATH="$HOME/.local/bin:$PATH"
        python -m pip install --upgrade pip setuptools
        python -m pip install pipenv
        pipenv sync
        pipenv run ./bin/ingest-gisaid --fetch
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GISAID_API_ENDPOINT: ${{ secrets.GISAID_API_ENDPOINT }}
        GISAID_USERNAME_AND_PASSWORD: ${{ secrets.GISAID_USERNAME_AND_PASSWORD }}
        SLACK_CHANNELS: "#covid19nextstrain"
        AWS_BATCH_QUEUE: nextstrain-job-queue
        AWS_BATCH_S3_BUCKET: ${{ secrets.BATCH_S3_BUCKET }}
        CPUS: 96
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        S3_SRC: ${{ secrets.S3_PREFIX }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        MEMORY: 126GiB
