name: '[branch] Ingest 2019-nCov/SARS-CoV-2 data from GISAID for nextstrain.org/ncov'

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - '**'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ingest
      run: |
        PATH="$HOME/.local/bin:$PATH"
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install pipenv
        pipenv sync
        pipenv run ./bin/ingest-gisaid
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GISAID_API_ENDPOINT: ${{ secrets.GISAID_API_ENDPOINT }}
        GISAID_USERNAME_AND_PASSWORD: ${{ secrets.GISAID_USERNAME_AND_PASSWORD }}
        S3_SRC: ${{ secrets.S3_PREFIX }}
        SLACK_CHANNELS: "#covid19nextstrain-test"
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        AWS_BATCH_QUEUE: nextstrain-job-queue
        AWS_BATCH_S3_BUCKET: ${{ secrets.BATCH_S3_BUCKET }}
        CPUS: 96
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        MEMORY: 126GiB
